#!/usr/bin/env bash

# disable window management
yabai -m config layout float

# enable window borders
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0XFF50FA7B
yabai -m config normal_window_border_color 0xFFBD93F9

# # Set all padding and gaps to 20pt (default: 0)
# yabai -m config top_padding    20
# yabai -m config bottom_padding 20
# yabai -m config left_padding   20
# yabai -m config right_padding  20
# yabai -m config window_gap     10

# # window opacity (default: off)
# # example: render all unfocused windows with 90% opacity
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

echo "yabai configuration loaded..."
