require('./plugins/completion')
require('./plugins/hop')
require('./plugins/ibl')
require('./plugins/lsp')
require('./plugins/nullls')
require('./plugins/nerdtree')
require('./plugins/telescope')
require('./plugins/trouble')
-- treesitter does not load consistently
require('./plugins/treesitter')
