require('./plugins/completion')
require('./plugins/hop')
require('./plugins/lsp')
require('./plugins/nullls')
require('./plugins/nerdtree')
require('./plugins/telescope')
require('./plugins/treesitter')
