name: CI

on:
  push:
    branches-ignore:
    - master
    - '[0-9]+.x'
    - '[0-9]+.[0-9]+.x'

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
    - name: Run commitlint
      run: npx commitlint --from origin/master --to HEAD --verbose
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Shellcheck
      run: ./scripts/utils/test.sh
